// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateRepoReducer from "../create_repo_reducer";
import FinishRepoReducer from "../finish_repo_reducer";
import IngestEdgesReducer from "../ingest_edges_reducer";
import IngestNodesReducer from "../ingest_nodes_reducer";
import JoinRoomReducer from "../join_room_reducer";
import SetFocusReducer from "../set_focus_reducer";
import StartWalkReducer from "../start_walk_reducer";
import StepWalkReducer from "../step_walk_reducer";

export type CreateRepoParams = __Infer<typeof CreateRepoReducer>;
export type FinishRepoParams = __Infer<typeof FinishRepoReducer>;
export type IngestEdgesParams = __Infer<typeof IngestEdgesReducer>;
export type IngestNodesParams = __Infer<typeof IngestNodesReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type SetFocusParams = __Infer<typeof SetFocusReducer>;
export type StartWalkParams = __Infer<typeof StartWalkReducer>;
export type StepWalkParams = __Infer<typeof StepWalkReducer>;

