// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  session: __t.string(),
  agentName: __t.string().name("agent_name"),
  repoId: __t.u64().name("repo_id"),
  online: __t.bool(),
  touches: __t.u32(),
  startedAt: __t.timestamp().name("started_at"),
  lastAt: __t.timestamp().name("last_at"),
});
