// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  repoId: __t.u64().name("repo_id"),
  nodeId: __t.u64().name("node_id"),
  path: __t.string(),
  note: __t.string(),
  status: __t.string(),
  askedBy: __t.identity().name("asked_by"),
  claimedBy: __t.string().name("claimed_by"),
  result: __t.string(),
  at: __t.timestamp(),
});
