// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  nodeId: __t.u64().primaryKey().name("node_id"),
  repoId: __t.u64().name("repo_id"),
  touches: __t.u32(),
  lastTool: __t.string().name("last_tool"),
  lastSession: __t.string().name("last_session"),
  explored: __t.bool(),
  lastAt: __t.timestamp().name("last_at"),
});
