// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  repoId: __t.u64().primaryKey().name("repo_id"),
  owner: __t.string(),
  repo: __t.string(),
  ref: __t.string(),
  filesSeen: __t.u32().name("files_seen"),
  filesIndexed: __t.u32().name("files_indexed"),
  truncated: __t.bool(),
  capped: __t.bool(),
  at: __t.timestamp(),
});
