// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  touchId: __t.u64().primaryKey().name("touch_id"),
  repoId: __t.u64().name("repo_id"),
  durationMs: __t.u32().name("duration_ms"),
  toolUseId: __t.string().name("tool_use_id"),
});
