// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Edge = __t.object("Edge", {
  id: __t.u64(),
  repoId: __t.u64(),
  src: __t.u64(),
  dst: __t.u64(),
  kind: __t.string(),
});
export type Edge = __Infer<typeof Edge>;

export const Frontier = __t.object("Frontier", {
  id: __t.u64(),
  walkId: __t.u64(),
  hop: __t.u32(),
  nodeId: __t.u64(),
  isTest: __t.bool(),
});
export type Frontier = __Infer<typeof Frontier>;

export const Node = __t.object("Node", {
  id: __t.u64(),
  repoId: __t.u64(),
  kind: __t.string(),
  name: __t.string(),
  qual: __t.string(),
});
export type Node = __Infer<typeof Node>;

export const Participant = __t.object("Participant", {
  identity: __t.identity(),
  name: __t.string(),
  repoId: __t.u64(),
  focusNode: __t.u64(),
  online: __t.bool(),
});
export type Participant = __Infer<typeof Participant>;

export const Repo = __t.object("Repo", {
  id: __t.u64(),
  slug: __t.string(),
  label: __t.string(),
  nodeCount: __t.u32(),
  edgeCount: __t.u32(),
  reachability: __t.f32(),
  status: __t.string(),
});
export type Repo = __Infer<typeof Repo>;

export const Verdict = __t.object("Verdict", {
  id: __t.u64(),
  walkId: __t.u64(),
  decision: __t.string(),
  recallPrior: __t.f32(),
  wilsonLb: __t.f32(),
  threshold: __t.f32(),
  reason: __t.string(),
  missedTest: __t.u64(),
});
export type Verdict = __Infer<typeof Verdict>;

export const Walk = __t.object("Walk", {
  id: __t.u64(),
  repoId: __t.u64(),
  origin: __t.u64(),
  k: __t.u32(),
  hop: __t.u32(),
  selected: __t.u32(),
  graphComplete: __t.bool(),
  done: __t.bool(),
  startedBy: __t.identity(),
});
export type Walk = __Infer<typeof Walk>;

