// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AgentSession = __t.object("AgentSession", {
  id: __t.u64(),
  session: __t.string(),
  agentName: __t.string(),
  repoId: __t.u64(),
  online: __t.bool(),
  touches: __t.u32(),
  startedAt: __t.timestamp(),
  lastAt: __t.timestamp(),
});
export type AgentSession = __Infer<typeof AgentSession>;

export const Edge = __t.object("Edge", {
  id: __t.u64(),
  repoId: __t.u64(),
  src: __t.u64(),
  dst: __t.u64(),
  kind: __t.string(),
});
export type Edge = __Infer<typeof Edge>;

export const ExplorationRequest = __t.object("ExplorationRequest", {
  id: __t.u64(),
  repoId: __t.u64(),
  nodeId: __t.u64(),
  path: __t.string(),
  note: __t.string(),
  status: __t.string(),
  askedBy: __t.identity(),
  claimedBy: __t.string(),
  result: __t.string(),
  at: __t.timestamp(),
});
export type ExplorationRequest = __Infer<typeof ExplorationRequest>;

export const Frontier = __t.object("Frontier", {
  id: __t.u64(),
  walkId: __t.u64(),
  hop: __t.u32(),
  nodeId: __t.u64(),
  isTest: __t.bool(),
});
export type Frontier = __Infer<typeof Frontier>;

export const NewLand = __t.object("NewLand", {
  key: __t.string(),
  repoId: __t.u64(),
  nodeId: __t.u64(),
  path: __t.string(),
  actor: __t.string(),
  at: __t.timestamp(),
});
export type NewLand = __Infer<typeof NewLand>;

export const NewLandSeq = __t.object("NewLandSeq", {
  repoId: __t.u64(),
  next: __t.u32(),
});
export type NewLandSeq = __Infer<typeof NewLandSeq>;

export const Node = __t.object("Node", {
  id: __t.u64(),
  repoId: __t.u64(),
  kind: __t.string(),
  name: __t.string(),
  qual: __t.string(),
});
export type Node = __Infer<typeof Node>;

export const NodeCov = __t.object("NodeCov", {
  nodeId: __t.u64(),
  repoId: __t.u64(),
  touches: __t.u32(),
  lastTool: __t.string(),
  lastSession: __t.string(),
  explored: __t.bool(),
  lastAt: __t.timestamp(),
});
export type NodeCov = __Infer<typeof NodeCov>;

export const NodeSummary = __t.object("NodeSummary", {
  nodeId: __t.u64(),
  repoId: __t.u64(),
  summary: __t.string(),
  model: __t.string(),
  at: __t.timestamp(),
});
export type NodeSummary = __Infer<typeof NodeSummary>;

export const Participant = __t.object("Participant", {
  identity: __t.identity(),
  name: __t.string(),
  repoId: __t.u64(),
  focusNode: __t.u64(),
  online: __t.bool(),
});
export type Participant = __Infer<typeof Participant>;

export const PathCache = __t.object("PathCache", {
  key: __t.string(),
  repoId: __t.u64(),
  nodeIds: __t.array(__t.u64()),
});
export type PathCache = __Infer<typeof PathCache>;

export const Repo = __t.object("Repo", {
  id: __t.u64(),
  slug: __t.string(),
  label: __t.string(),
  nodeCount: __t.u32(),
  edgeCount: __t.u32(),
  reachability: __t.f32(),
  status: __t.string(),
});
export type Repo = __Infer<typeof Repo>;

export const RepoIndex = __t.object("RepoIndex", {
  repoId: __t.u64(),
  owner: __t.string(),
  repo: __t.string(),
  ref: __t.string(),
  filesSeen: __t.u32(),
  filesIndexed: __t.u32(),
  truncated: __t.bool(),
  capped: __t.bool(),
  at: __t.timestamp(),
});
export type RepoIndex = __Infer<typeof RepoIndex>;

export const Touch = __t.object("Touch", {
  id: __t.u64(),
  repoId: __t.u64(),
  nodeId: __t.u64(),
  path: __t.string(),
  tool: __t.string(),
  session: __t.string(),
  agentName: __t.string(),
  at: __t.timestamp(),
});
export type Touch = __Infer<typeof Touch>;

export const Verdict = __t.object("Verdict", {
  id: __t.u64(),
  walkId: __t.u64(),
  decision: __t.string(),
  recallPrior: __t.f32(),
  wilsonLb: __t.f32(),
  threshold: __t.f32(),
  reason: __t.string(),
  missedTest: __t.u64(),
});
export type Verdict = __Infer<typeof Verdict>;

export const Walk = __t.object("Walk", {
  id: __t.u64(),
  repoId: __t.u64(),
  origin: __t.u64(),
  k: __t.u32(),
  hop: __t.u32(),
  selected: __t.u32(),
  graphComplete: __t.bool(),
  done: __t.bool(),
  startedBy: __t.identity(),
});
export type Walk = __Infer<typeof Walk>;

