// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  walkId: __t.u64().name("walk_id"),
  decision: __t.string(),
  recallPrior: __t.f32().name("recall_prior"),
  wilsonLb: __t.f32().name("wilson_lb"),
  threshold: __t.f32(),
  reason: __t.string(),
  missedTest: __t.u64().name("missed_test"),
});
