// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  repoId: __t.u64().name("repo_id"),
  origin: __t.u64(),
  k: __t.u32(),
  hop: __t.u32(),
  selected: __t.u32(),
  graphComplete: __t.bool().name("graph_complete"),
  done: __t.bool(),
  startedBy: __t.identity().name("started_by"),
});
